eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9291/eureka/,http://localhost:9293/eureka/,http://localhost:9293/eureka/
server:
  port: 8764
spring:
  application:
    name: service-ribbon
